//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:servicioweb", ConfigurationName="ServiceReference1.serviciowebPortType")]
    public interface serviciowebPortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.appcontacto.com.co/WServices/index.php/InsercionMensaje", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="respuesta")]
        System.Threading.Tasks.Task<ServiceReference1.informacion> InsercionMensajeAsync(string numero, string mensaje, string nota, string usuario, string clave, string programado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.appcontacto.com.co/WServices/index.php/EnviarMensaje", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="respuesta")]
        System.Threading.Tasks.Task<string> EnviarMensajeAsync(string numero, string mensaje, string nota, string usuario, string clave, string programado);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:servicioweb")]
    public partial class informacion
    {
        
        private string salidaField;
        
        /// <remarks/>
        public string salida
        {
            get
            {
                return this.salidaField;
            }
            set
            {
                this.salidaField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface serviciowebPortTypeChannel : ServiceReference1.serviciowebPortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class serviciowebPortTypeClient : System.ServiceModel.ClientBase<ServiceReference1.serviciowebPortType>, ServiceReference1.serviciowebPortType
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public serviciowebPortTypeClient() : 
                base(serviciowebPortTypeClient.GetDefaultBinding(), serviciowebPortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.serviciowebPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public serviciowebPortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(serviciowebPortTypeClient.GetBindingForEndpoint(endpointConfiguration), serviciowebPortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public serviciowebPortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(serviciowebPortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public serviciowebPortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(serviciowebPortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public serviciowebPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.informacion> InsercionMensajeAsync(string numero, string mensaje, string nota, string usuario, string clave, string programado)
        {
            return base.Channel.InsercionMensajeAsync(numero, mensaje, nota, usuario, clave, programado);
        }
        
        public System.Threading.Tasks.Task<string> EnviarMensajeAsync(string numero, string mensaje, string nota, string usuario, string clave, string programado)
        {
            return base.Channel.EnviarMensajeAsync(numero, mensaje, nota, usuario, clave, programado);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.serviciowebPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.serviciowebPort))
            {
                return new System.ServiceModel.EndpointAddress("http://www.appcontacto.com.co/WServices/index.php");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return serviciowebPortTypeClient.GetBindingForEndpoint(EndpointConfiguration.serviciowebPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return serviciowebPortTypeClient.GetEndpointAddress(EndpointConfiguration.serviciowebPort);
        }
        
        public enum EndpointConfiguration
        {
            
            serviciowebPort,
        }
    }
}
